---
title: Quarto Installation and Setup
---

::: {.unit-overview}
# Overview

This unit guides you through the installation and initial setup of Quarto. You will learn how to install Quarto and make sure it's up and running.

:::

<!-- end unit-overview div -->

::: {.unit-goals}
# Goals

- Successfully install Quarto on your system.
::: 
<!-- end unit-goals div -->

<!--
::: {.unit-video}
# Video, slides and audio transcript

Below is the video for this unit. Here are [the slides shown in the video](), and here is the [audio transcript](), as well as a [text version of the transcript]().

<iframe class="video" src="https://www.youtube.com/embed/tiwJzvqFgmY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

::: 
-->
<!-- end unit-video div -->

::: {.unit-reading}
# Reading


## Installing Quarto 

Visit the [Get started page](https://quarto.org/docs/get-started/) on the Quarto website to download and install Quarto. 

Install it like you would any other software. If you don't have administrator rights to your computer, choose the user installation, which hopefully will work without admin rights. If not, you might need to have your admin install Quarto for you.


## Testing/using Quarto

Quarto is a command-line tool. That means you run it from a terminal (Mac/Linux) or command prompt (Windows). We will essentially always call it from within Positron. 

But to test it, open a terminal/command prompt. If you are on Windows, look for the "Command Prompt" or "Terminal" application and open it. If you are on a Mac, open the "Terminal" application. At the `>` symbol, type the following:

```bash
quarto --version
```

If the install worked, you should see it show the version of the software you just downloaded and installed.

If you ever need to see what commands you can use with Quarto, type:
```bash
quarto --help
```

Though to be honest, what you get is not that informative. It's just a quick way to look up syntax if you forgot it. To learn in detail what each of these commands do, refer to the Quarto website and its documentation.


## Quarto configuration

Quarto interacts with a lot of other tools. Not all are needed, depending on what you want to do. To see this list of tools and if they are available on your system, type this into the console/terminal:

```bash
quarto check
```

If you want to create PDF documents -- which is often very useful -- you will need to install a TeX distribution. Quarto recommends `TinyTeX` for this. You can install it by typing the following command into the console:

```bash
quarto install tinytex
```

If you are already familiar with TeX distributions and have a preferred one, you can also use that one. See the [Quarto documentation on PDF output](https://quarto.org/docs/output-formats/pdf-basics.html) for more details.



::: 
<!-- end unit-reading div -->

::: {.unit-summary}
# Summary

In this unit, you learned how to install Quarto and perform initial setup tasks. You also learned how to install a TeX distribution such as TinyTeX to enable PDF output generation.

::: 
<!-- end unit-summary div -->

::: {.unit-resources}
# Further Resources

- The [Official Quarto website](https://quarto.org) has extensive documentation and tutorials.

::: 
<!-- end unit-resources div -->

::: {.unit-quiz}
# Test yourself

```{r quarto-install-setup-quiz}
#| echo: false
#| results: "asis"
quizzes <- list("quarto-install-setup-quiz-1.Rmd", "quarto-install-setup-quiz-2.Rmd", "quarto-install-setup-quiz-3.Rmd")
exams2forms::exams2forms(file = quizzes, title = 'quarto-install-setup-quiz')
```
::: 
<!-- end unit-quiz div -->

::: {.unit-exercise}
# Practice

There's nothing else to practice for now. We hope the install worked and you verified by trying the commands above. 


::: 
<!-- end unit-exercise div -->
