---
title: Introduction to IDEs and Positron
---

::: {.unit-overview}
# Overview

This unit provides a high‑level introduction to integrated development environments (IDEs) in general and Positron in particular. 

:::
<!-- end unit-overview div -->

::: {.unit-goals}
# Goals

* Understand what an Integrated Development Environment is and how it differs from a plain text editor.  
* Recognise the common building blocks shared by most IDEs.  
* Know what is unique about Positron.  

:::
<!-- end unit-goals div -->

<!--
::: {.unit-video}
# Video, slides and audio transcript

Below is the video for this unit. Here are [the slides shown in the video](), as well as a [text version of the transcript]().

<iframe class="video" src="https://www.youtube.com/embed/VIDEO_ID" title="Introduction to IDEs and Positron" allowfullscreen></iframe>

:::
-->
<!-- end unit-video div -->


::: {.unit-reading}
# Reading


## Integrated Development Environments (IDEs)

Any kind of data analysis and modeling project generally requires interacting with data, writing and debugging code, managing files, producing figures and tables, generating manuscripts or reports, and more. It is convenient to do all this through a single interface, at least as much as possible. This is where the concept of an Integrated Development Environment (IDE) comes in. It is a piece of software that not only lets you write code, but also allows you to do many other project functions through a single interface.

Another way to think of IDEs is that they are code editors with a lot of additional bells and whistles. The idea is that one has all the functionality one needs to not just write code, but also to run it and debug it, to look at results, to manage files, etc. in a single place. That's what an IDE tries to do.

Most IDEs share certain features: 

* The editor is where you write your code. It usually offers syntax highlighting, intelligent completion, and many other features that make coding life easier. 
* The console/terminal area (called panel in Positron) is where you can interact with other pieces of software, such as programming languages (e.g. R, Python, Julia), where you see error messages, and where you can debug.
* An area (it is the left side bar for Positron) where you can interact with files, perform version control with GitHub, manage extensions, and other operations.
* Another area (usually the right side bar in Positron) that shows outputs such as figures, allows you to interactively explore data and objects generated by your code, and provides further functionality.

Having all these features inside one platform makes modern IDEs rather powerful. The flip-side is that it takes time getting used to all the functionality. But it's generally worth the effort since IDEs make coding and related project work much more efficient. Most IDEs are highly configurable, so you can arrange the items you want to see and where to see them. We'll discuss that a bit more shortly.


## The Positron IDE

Some IDEs focus on a specific programming language (e.g., RStudio), others are very language-agnostic (e.g., VS Code). Positron is a bit in the middle. It's a fairly new IDE developed by the folks from Posit, who previously developed RStudio. The idea is that it's an IDE that has strong integration for certain programming languages -- currently the main focus is on R and Phython -- while also allowing you to work with other languages, such as Julia.

Positron is cross-platform and free. Because it's from the same folks that created Quarto, it plays nicely with it. It has many of the nice, user-friendy features of RStudio, but has been designed to be more flexible, extensible and supporting more languages compared to RStudio.

Positron is a spin-off of VS Code, which is a very popular IDE developed by Microsoft. Positron builds on top of VS Code and adds a lot of functionality that is specifically useful for data analysis and modeling projects. Because of this, Positron also supports a wide range of extensions (add-ons) that can further enhance its functionality. We'll discuss extensions in more detail in a later unit.

## Positron versus other IDEs

We think that currently, Positron is a great choice because it plays nicely with Quarto and R, supports Phthon, Julia and Git/GitHub, and is likely to become an increasingly popular and powerful editor for projects related to modeling and data analysis. 

That said, almost everything we discuss and teach could also be done in a different IDE, such as VS Code or RStudio. While the instructions we provide are often Positron specific, you should be able to get everything working in pretty much any IDE.


:::
<!-- end unit-reading div -->


::: {.unit-summary}
# Summary

This unit explained what an IDE is, briefly introduced Positron and explained why we use it.

:::
<!-- end unit-summary div -->


::: {.unit-resources}
# Further Resources

* [The offical Positron website](https://positron.posit.co/)
* [The official VS Code website](https://code.visualstudio.com/) - VS Code is a very popular editor, and it is the basis for Positron. A lot of information about VS Code will also apply to Positron.

:::
<!-- end unit-resources div -->


::: {.unit-quiz}
# Test yourself

```{r positron-introduction-quiz}
#| echo: false
#| results: "asis"
quizzes <- list("positron-introduction-quiz-1.Rmd", "positron-introduction-quiz-2.Rmd", "positron-introduction-quiz-3.Rmd")
exams2forms::exams2forms(file = quizzes, title = 'positron-introduction-quiz')
```
:::
<!-- end unit-quiz div -->


::: {.unit-exercise}
# Practice

* Read through the [getting started](https://positron.posit.co/welcome.html) section of the Positron website and make sure your computer is ready for the Positron installation.
* If you want to learn more about Positron in general, watch the (somewhat long) [Introducing Positron video](https://youtu.be/8uRcB34Hhsw?si=qLlwgEJ5BE7OKoPT).  


:::
<!-- end unit-exercise div -->
