---
title: "Course Overview: A brief introduction to Positron"
---

::: {.course-overview}
# Course Overview

This short course provides a basic introduction to the Positron editor and Integrated Development Environment (IDE).

We are using Positron throughout QSPL. This short course provides you with the basics to be able to go through our main courses.

If you want to use an alternative editor (e.g., RStudio, VS Code, Cursor), you can certainly do so. You will just have to be able to implement our instructions in the editor of your choice. 

:::


::: {.course-goals}
# Course Goals

* Understand the benefits of using an Integrated Development Environment (IDE) such as Positron.
* Install Positron.
* Know how to add extensions to Positron.
* Be familiar with the basic features of Positron. 

:::



::: {.course-content}
# Course Content

The course consists of these modules and units.

## Module 1

- [Introduction to IDEs and Positron](positron-introduction/positron-introduction.qmd)
- [Positron Installation and Setup](positron-install-setup/positron-install-setup.qmd)
- [Positron Extensions](positron-extensions/positron-extensions.qmd)
- [Basic Positron Features](positron-features/positron-features.qmd)
- [Configuring Positron](positron-configuration/positron-configuration.qmd)
- [Basic Positron Use](positron-use/positron-use.qmd)
- [Further Positron Resources](positron-resources/positron-resources.qmd)
:::