---
title: Title of unit
---

::: {.unit-overview}
# Overview

This unit provides a brief..

:::
<!-- end unit-overview div -->

::: {.unit-goals}
# Goals

* Know how to do X.
* Be able to mess with Y.

::: 
<!-- end unit-goals div -->

<!--
::: {.unit-video}
# Video

Watch the unit video on YouTube: [YouTube video](https://www.youtube.com/watch?v=VIDEO_ID)

<iframe class="video" src="https://www.youtube.com/embed/VIDEO_ID" title="Unit video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

:::
-->
<!-- end unit-video div -->

::: {.unit-slides}
# Slides

View the slide deck for this unit: [Slides](unit-template-slides.qmd){target="_blank" rel="noopener"}

:::
<!-- end unit-slides div -->


::: {.unit-transcript}
# Text and Audio Transcripts

Read the text transcript: [Text transcript](unit-template-transcript.md)

<!--
Listen to the audio transcript: [Audio transcript](AUDIO_LINK)
-->
::: 
<!-- end unit-transcript div -->


::: {.unit-reading}
# Reading

## Introduction

This unit is about XYZ

## A topic

Sub-levels as needed.
Use markdown level 2 headings and below within this section. 

### Subtopic 1

A sublevel for this topic.

### Subtopic 2

Another sublevel for this topic.

## Another topic 

Not all topics need further sub-level division.

## Yet another topic 

This topic also doesn't have subdivision.


::: 
<!-- end unit-reading div -->


::: {.unit-summary}
# Summary

In this unit, we covered XYZ.

::: 
<!-- end unit-summary div -->


::: {.unit-resources}
# Further Resources

* This is a [good additional reading](URL).
* Here is some more good information.

::: 
<!-- end unit-resources div -->


::: {.unit-quiz}
# Test yourself

```{r topic-title-of-quiz}
| echo: false
| results: "asis"
# quizzes <- list("topic-title-quiz-1.Rmd", "topic-title-quiz-2.Rmd", "topic-title-quiz-3.Rmd")
# exams2forms::exams2forms(file = quizzes, title = 'topic-title-of-quiz')
```
::: 
<!-- end unit-quiz div -->



::: {.unit-exercise}
# Practice

* Do task X.
* Do task Y.

::: 
<!-- end unit-exercise div -->
