---
title: Further Resources
subtitle: ""
---

::: {.unit-overview}
# Overview

This unit provides a few pointers to resources for learning more about Git and GitHub.

:::
<!-- end unit-overview div -->

::: {.unit-goals}
# Goals

* Know where to find additional Git and GitHub documentation.

:::
<!-- end unit-goals div -->

<!--
::: {.unit-video}
# Video

Watch the unit video on YouTube: [YouTube video](https://www.youtube.com/watch?v=VIDEO_ID)

<iframe class="video" src="https://www.youtube.com/embed/VIDEO_ID" title="Unit video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

:::
-->
<!-- end unit-video div -->

::: {.unit-slides}
# Slides

View the slide deck for this unit: [Slides](github-resources-slides.qmd)

:::
<!-- end unit-slides div -->

::: {.unit-transcript}
# Text and Audio Transcripts

Read the text transcript: [Text transcript](github-resources-transcript.md)

<!--
Listen to the audio transcript: [Audio transcript](AUDIO_LINK)
-->

::: 
<!-- end unit-transcript div -->
::: {.unit-reading}
# Reading

## Official documentation

The official documentation for Git and GitHub is extensive and well maintained. 
You can find the [GitHub Docs](https://docs.github.com/) on the GitHub website and the [Git learn section](https://git-scm.com/learn) on the Git website.



## Community Resources

The [GitHub community site](https://github.com/community) is a good place to ask questions and find answers related to GitHub.

There is even a game, called [Oh My Git!](https://ohmygit.org/) that is meant to teach you Git while playing. We have not tried it, so we don't know if it's entertaining and/or useful.


:::
<!-- end unit-reading div -->


::: {.unit-summary}
# Summary

This unit listed a few additional resources. These days, AI tools are also often very helpful in answering questions about Git and GitHub. 

:::
<!-- end unit-summary div -->


::: {.unit-resources}
# Further Resources

See above.

:::
<!-- end unit-resources div -->



::: {.unit-quiz}
# Test yourself

```{r github-resources-quiz}
#| echo: false
#| results: "asis"
quizzes <- list("github-resources-quiz-1.Rmd", "github-resources-quiz-2.Rmd", "github-resources-quiz-3.Rmd")
exams2forms::exams2forms(file = quizzes, title = 'github-resources-quiz')
```
:::

<!-- end unit-quiz div -->


::: {.unit-exercise}
# Practice
* Ask your favorite LLM AI tool to explain some Git/GitHub concept that you find confusing. As you learn about it, ask for examples, further explanations, etc. You can also ask it to give you pointers to additional resources for that specific topic.
* Repeat for a different topic and/or a different AI tool.

:::
<!-- end unit-exercise div -->
