---
title: Basics of Coding in Julia
---

::: {.unit-overview}
# Overview

This unit introduces the core syntax needed to read and write simple Julia programs.

:::
<!-- end unit-overview div -->

::: {.unit-goals}
# Goals

* Create variables and understand basic types.
* Define and call functions.
* Use conditionals and loops.

::: 
<!-- end unit-goals div -->

<!--
::: {.unit-video}
# Video

Watch the unit video on YouTube: [YouTube video](https://www.youtube.com/watch?v=VIDEO_ID)

<iframe class="video" src="https://www.youtube.com/embed/VIDEO_ID" title="Unit video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

:::
-->
<!-- end unit-video div -->

<!--
::: {.unit-slides}
# Slides

View the slide deck for this unit: [Slides](julia-coding-basics-slides.qmd){target="_blank" rel="noopener"}

:::
-->
<!-- end unit-slides div -->


<!--
::: {.unit-transcript}
# Text and Audio Transcripts

Read the text transcript: [Text transcript](julia-coding-basics-transcript.md)

:::
-->
<!-- end unit-transcript div -->


::: {.unit-reading}
# Reading

## Variables and types

Julia uses dynamic typing, but it can still be fast when code is written with type stability in mind. You can inspect types with typeof() when needed.

## Functions

Functions are defined with the function keyword or short arrow syntax. Julia also supports multiple dispatch, meaning you can define different methods for different argument types.

## Control flow

Use if statements for branching and for or while loops for repetition. These constructs look similar to other languages.

## Collections

Arrays, tuples, and dictionaries are core data structures. Arrays are 1-indexed in Julia, which is common in scientific computing.

::: 
<!-- end unit-reading div -->


::: {.unit-summary}
# Summary

We covered Julia basics: variables, functions, control flow, and core data structures.

::: 
<!-- end unit-summary div -->


::: {.unit-resources}
# Further Resources

* Julia manual: https://docs.julialang.org/en/v1/manual/
* Julia by Example: https://juliabyexample.helpmanual.io/

::: 
<!-- end unit-resources div -->


::: {.unit-quiz}
# Test yourself

```{r julia-coding-basics-quiz}
#| echo: false
#| results: "asis"
quizzes <- list('julia-coding-basics-quiz-1.Rmd', 'julia-coding-basics-quiz-2.Rmd', 'julia-coding-basics-quiz-3.Rmd')
exams2forms::exams2forms(file = quizzes, title = 'julia-coding-basics-quiz')
```
:::
<!-- end unit-quiz div -->



::: {.unit-exercise}
# Practice

* Create a vector and compute its mean.
* Write a function that returns the larger of two numbers.
* Loop over a list of values and print those above a threshold.

::: 
<!-- end unit-exercise div -->
