---
title: A collection of links to AI resources
subtitle: ""
---

::: {.unit-overview}
# Overview

This unit consists mainly of a collection of links to AI resources that might be useful. I tried to group them into themes and provide a bit of commentary. The focus is on generative AI tools.

:::
<!-- end unit-overview div -->

::: {.unit-goals}
# Goals

By the end of the unit, you should:

* Be aware of a few places where you can learn more about AI.

:::
<!-- end unit-goals div -->

<!--
::: {.unit-video}
# Video, slides and audio transcript

Below is the video for this unit. Here are [the slides shown in the video](), and here is the [audio transcript](), as well as a [text version of the transcript]().

<iframe class="video" src="https://www.youtube.com/embed/VIDEO_ID" title="A collection of links to AI resources" allowfullscreen></iframe>

:::
-->
<!-- end unit-video div -->


::: {.unit-reading}
# Reading

## Introduction

Below is a curated list of resources grouped by theme. Use them to go deeper on specific topics, or to find a few reliable sources to follow over time.

## AI in general

* [One Useful Thing](https://www.oneusefulthing.org/) is a Substack blog by Ethan Mollick where he discusses ideas around (generative) AI from a very applied user perspective. You might find a lot of what he writes echoed in my writing, because that's where I get a lot of my information from 😁.

* [Unconfuse Me](https://www.gatesnotes.com/Podcast) is a podcast by Bill Gates that covers all kinds of topics, but has a few interesting AI-themed ones, namely (as of this writing) episodes 2 and 5.

* [DeepLearning.AI](https://www.deeplearning.ai/) is a platform/company that offers a lot of teaching material related to AI. Some of the materials are free.

* A really good (but non-free) book is [*Artificial Intelligence: A Guide for Thinking Humans*](https://melaniemitchell.me/aibook/). The author, Melanie Mitchell, also has [an AI blog](https://aiguide.substack.com/) that is worth checking out.

* This [Coursera course](https://www.coursera.org/learn/generative-ai-for-everyone) gives a brief, non-technical introduction to current LLM AI tools (such as GPT).

## Technical aspects of AI

* The [Deep Learning Chapter of *HMLR*](https://bradleyboehmke.github.io/HOML/deep-learning.html) provides a nice basic introduction.

* The [Statquest Youtube channel](https://www.youtube.com/@statquest) has multiple videos with nice explanations on various AI related topics, at times going fairly deep into the technical details, while still being rather easy to understand.

## AI and R

* These [materials from a recent workshop by Phil Bowsher](https://github.com/philbowsher/Workshop-R-Tensorflow-Scientific-Computing) describe using Tensorflow to do deep learning/AI in R.

## AI and teaching

- [Wharton Interactive](https://interactive.wharton.upenn.edu/teaching-with-ai/) is an initiative by Ethan and Lilach Mollick and colleagues at Wharton that - among other things - looks at the use of AI for teaching and learning. The website contains some interesting ideas and links to papers that look further into AI use.

- MIT has a nice collection of [AI learning resources](https://mitsloanedtech.mit.edu/ai/). The focus is on using those tools for teaching/learning.

## AI and Coding

- [GitHub Copilot](https://github.com/features/copilot) is meant specifically for coding. It is generally not free, but if you get the [GitHub student developer pack](https://education.github.com/pack) you get it included. The [GitHub Copilot documentation](https://docs.github.com/en/copilot) contains a lot of good information to get started and to dig deeper.

:::
<!-- end unit-reading div -->


::: {.unit-summary}
# Summary

Use this page as a jumping-off point and revisit it as the AI landscape evolves. If you find additional high-quality resources, let me know so I can keep the list current.

:::
<!-- end unit-summary div -->


::: {.unit-resources}
# Further Resources

If you have suggestions for new links or corrections, please send them along.

:::
<!-- end unit-resources div -->


::: {.unit-quiz}
# Test yourself

```{r ai-resources-quiz}
#| echo: false
#| results: "asis"
quizzes <- list("ai-resources-quiz-1.Rmd", "ai-resources-quiz-2.Rmd", "ai-resources-quiz-3.Rmd")
exams2forms::exams2forms(file = quizzes, title = 'ai-resources-quiz')
```
:::
<!-- end unit-quiz div -->



::: {.unit-exercise}
# Practice

* Pick one resource from each section and skim it for 10 minutes.
* Identify one resource that you could follow regularly for updates.
* Share a favorite AI resource with the course team or peers.

:::
<!-- end unit-exercise div -->
