---
title: Julia Coding Tips
---

::: {.unit-overview}
# Overview

This unit shares practical tips for working with Julia.

:::
<!-- end unit-overview div -->

::: {.unit-goals}
# Goals

* Read and use error messages to debug.
* Work in small steps to avoid confusion.
* Use built-in help and documentation.

::: 
<!-- end unit-goals div -->

<!--
::: {.unit-video}
# Video

Watch the unit video on YouTube: [YouTube video](https://www.youtube.com/watch?v=VIDEO_ID)

<iframe class="video" src="https://www.youtube.com/embed/VIDEO_ID" title="Unit video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

:::
-->
<!-- end unit-video div -->

<!--
::: {.unit-slides}
# Slides

View the slide deck for this unit: [Slides](julia-coding-tips-slides.qmd){target="_blank" rel="noopener"}

:::
-->
<!-- end unit-slides div -->


<!--
::: {.unit-transcript}
# Text and Audio Transcripts

Read the text transcript: [Text transcript](julia-coding-tips-transcript.md)

:::
-->
<!-- end unit-transcript div -->


::: {.unit-reading}
# Reading

## Work in small steps

Run code frequently and keep changes small. This helps you find the exact line that introduced a bug.

## Read errors carefully

Julia errors often include a stack trace that points to the source of the problem. Use it to narrow down the cause.

## Use help effectively

In the REPL, type ? to open help mode. You can search for functions and see short examples.

::: 
<!-- end unit-reading div -->


::: {.unit-summary}
# Summary

We covered simple habits that make Julia coding smoother and easier to debug.

::: 
<!-- end unit-summary div -->


::: {.unit-resources}
# Further Resources

* Julia error handling docs: https://docs.julialang.org/en/v1/manual/control-flow/

::: 
<!-- end unit-resources div -->


::: {.unit-quiz}
# Test yourself

```{r julia-coding-tips-quiz}
#| echo: false
#| results: "asis"
quizzes <- list('julia-coding-tips-quiz-1.Rmd', 'julia-coding-tips-quiz-2.Rmd', 'julia-coding-tips-quiz-3.Rmd')
exams2forms::exams2forms(file = quizzes, title = 'julia-coding-tips-quiz')
```
:::
<!-- end unit-quiz div -->



::: {.unit-exercise}
# Practice

* Introduce a small error and fix it using the stack trace.
* Look up a function in help mode and read its signature.
* Refactor a short script into smaller steps.

::: 
<!-- end unit-exercise div -->
