---
title: Further Julia Resources
---

::: {.unit-overview}
# Overview

This unit lists resources for learning more Julia.

:::
<!-- end unit-overview div -->

::: {.unit-goals}
# Goals

* Know where to find official documentation.
* Identify quality tutorials and references.
* Plan next steps for continued learning.

::: 
<!-- end unit-goals div -->

<!--
::: {.unit-video}
# Video

Watch the unit video on YouTube: [YouTube video](https://www.youtube.com/watch?v=VIDEO_ID)

<iframe class="video" src="https://www.youtube.com/embed/VIDEO_ID" title="Unit video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

:::
-->
<!-- end unit-video div -->

::: {.unit-slides}
# Slides

View the slide deck for this unit: [Slides](julia-further-resources-slides.qmd)

:::
<!-- end unit-slides div -->


::: {.unit-transcript}
# Text and Audio Transcripts

Read the text transcript: [Text transcript](julia-further-resources-transcript.md)

<!--
Listen to the audio transcript: [Audio transcript](AUDIO_LINK)
-->
::: 
<!-- end unit-transcript div -->


::: {.unit-reading}
# Reading

## Official documentation

The Julia manual is the best reference for language features and the standard library.

## Tutorials and examples

Community tutorials and example collections help you learn by doing. Start with small examples and expand.

## Community and help

The Julia community is active in forums and chat. Learn to ask clear, specific questions when you need help.

::: 
<!-- end unit-reading div -->


::: {.unit-summary}
# Summary

We highlighted documentation and learning resources for continued study.

::: 
<!-- end unit-summary div -->


::: {.unit-resources}
# Further Resources

* Julia documentation: https://docs.julialang.org
* Julia Discourse forum: https://discourse.julialang.org/
* Julia community: https://julialang.org/community/

::: 
<!-- end unit-resources div -->


::: {.unit-quiz}
# Test yourself

```{r julia-further-resources-quiz}
#| echo: false
#| results: "asis"
quizzes <- list('julia-further-resources-quiz-1.Rmd', 'julia-further-resources-quiz-2.Rmd', 'julia-further-resources-quiz-3.Rmd')
exams2forms::exams2forms(file = quizzes, title = 'julia-further-resources-quiz')
```
:::
<!-- end unit-quiz div -->



::: {.unit-exercise}
# Practice

* Bookmark the Julia docs and the Discourse forum.
* Find one tutorial that matches your learning goals.
* Identify a package you want to explore next.

::: 
<!-- end unit-exercise div -->
