---
title: Using Julia Environments
---

::: {.unit-overview}
# Overview

This unit explains Julia project environments and why they matter.

:::
<!-- end unit-overview div -->

::: {.unit-goals}
# Goals

* Understand what an environment is.
* Create and activate a project environment.
* Use environments to reproduce results.

::: 
<!-- end unit-goals div -->

<!--
::: {.unit-video}
# Video

Watch the unit video on YouTube: [YouTube video](https://www.youtube.com/watch?v=VIDEO_ID)

<iframe class="video" src="https://www.youtube.com/embed/VIDEO_ID" title="Unit video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

:::
-->
<!-- end unit-video div -->

::: {.unit-slides}
# Slides

View the slide deck for this unit: [Slides](julia-environments-slides.qmd)

:::
<!-- end unit-slides div -->


::: {.unit-transcript}
# Text and Audio Transcripts

Read the text transcript: [Text transcript](julia-environments-transcript.md)

<!--
Listen to the audio transcript: [Audio transcript](AUDIO_LINK)
-->
::: 
<!-- end unit-transcript div -->


::: {.unit-reading}
# Reading

## Why environments

Environments isolate project dependencies so packages do not conflict across projects. This makes your work more reproducible.

## Creating an environment

In a project folder, start Julia and run ] to enter package mode, then activate . to use that folder as the active environment.

## Reproducing a project

If you have a Project.toml and Manifest.toml, you can run instantiate in package mode to install the exact dependencies.

::: 
<!-- end unit-reading div -->


::: {.unit-summary}
# Summary

We explained how environments isolate dependencies and how to activate and reproduce them.

::: 
<!-- end unit-summary div -->


::: {.unit-resources}
# Further Resources

* Julia environments guide: https://pkgdocs.julialang.org/v1/environments/

::: 
<!-- end unit-resources div -->


::: {.unit-quiz}
# Test yourself

```{r julia-environments-quiz}
#| echo: false
#| results: "asis"
quizzes <- list('julia-environments-quiz-1.Rmd', 'julia-environments-quiz-2.Rmd', 'julia-environments-quiz-3.Rmd')
exams2forms::exams2forms(file = quizzes, title = 'julia-environments-quiz')
```
:::
<!-- end unit-quiz div -->



::: {.unit-exercise}
# Practice

* Create a new project folder and activate it.
* Add a package inside the environment and verify it is recorded.
* Instantiate an environment from an existing Project.toml.

::: 
<!-- end unit-exercise div -->
