---
title: A brief introduction to AI tools 
---

::: {.course-overview}
# Course Overview

This course provides a brief introduction to AI tools that work nicely with the other tools in our stack.

As with the other courses, this is a very brief _getting started_ introduction. It will hopefully be enough to get you set up and running.

:::


::: {.course-goals}
# Course Goals

-   Know what AI tolls are useful for R/Positron/etc.
-   Install and set up various AI tools.
-   Be familiar with some basic AI use.


:::

<!--
::: {.course-stats}
# Course Stats

- N videos (X minutes)
- N modules, M units
- N exercises 
- Price: free

:::
-->



::: {.course-prerequisites}
# Course Prerequisites

We assume you have the following tools up and running at the level covered in our other brief introduction courses:

* [A brief Introduction to Positron course](fc1-intro-positron.qmd). 
* [A brief Introduction to Git/GitHub course](fc3-intro-github.qmd).
* [A brief Introduction to R course](fc4-intro-r.qmd).
* [A brief Introduction to Quarto course](fc2-intro-quarto.qmd).
<!-- * We further assume that you have R and/or Julia installed and can use it at the level covered in our [Brief Introduction to R course](fc4-intro-r.qmd) and [Brief Introduction to Julia course](fc5-intro-julia.qmd). -->

:::



::: {.course-content}
# Course Content

The course covers these topics (and more):

- Introduction
- Setup of AI tools
- Basic use
- Further Resources
:::


::: {.course-getstarted}
# Get started

[Click here to start this course.](/courses/fc5-intro-ai/intro-ai-overview.qmd)

:::
