---
title: "Creating an online portfolio" 
subtitle: ""
---

::: {.course-overview}
# Course Overview

This course gets you started at using Positron, Git/GitHub and Quarto to set up a website that will be your portfolio for exercises and projects.
:::


::: {.course-goals}
# Course Goals

* Know why having a public portfolio is a good idea.
* Be able to create a portfolio website using Positron, Git/GitHub and Quarto.
* Be ready to use your portfolio for future exercises and projects.

:::


<!--
::: {.course-stats}
# Course Stats

- N videos (X minutes)
- N modules, M units
- N exercises 
- Price: free

:::
-->


::: {.course-prerequisites}
# Course Prerequisites

* We assume you have Positron up and running and can use it at the level covered in our [**Brief Introduction to Positron** course](fc1-intro-positron.qmd). 
* We further assume that you have R installed and can use it at the level covered in our [Brief Introduction to R course](fc2a-intro-r.qmd).
* We also assume you have a basic knowledge of Quarto and can use it at the level covered in our [Brief Introduction to Quarto course](fc3-intro-quarto.qmd).
* We also assume you have Git/GitHub set up and can use it at the level covered in our [Brief Introduction to Git/GitHub course](fc5-intro-github.qmd).
<!-- * We further assume that you have R and/or Julia installed and can use it at the level covered in our [Brief Introduction to R course](fc4-intro-r.qmd) and [Brief Introduction to Julia course](fc5-intro-julia.qmd). -->

:::


::: {.course-content}
# Course Content

The course covers these topics (and more):

- Motivation
- Setup
- First content creation
- Further Resources

:::


::: {.course-getstarted}
# Get started

[Click here to start this course.](/courses/fc6-portfolio-creation/portfolio-creation-toc.qmd)


:::
