---
title: Online portfolio introduction
---

::: {.unit-overview}
# Overview
In this unit, we discuss what an online portfolio is, and why having one is a good idea.
:::

::: {.unit-goals}
# Goals
* Know what an online portfolio is.
* Know why it's good to have an online portfolio.
:::

<!--
::: {.unit-video}
# Video

Watch the unit video on YouTube: [YouTube video](https://www.youtube.com/watch?v=VIDEO_ID)

<iframe class="video" src="https://www.youtube.com/embed/VIDEO_ID" title="Unit video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

:::
-->
<!-- end unit-video div -->

::: {.unit-slides}
# Slides

View the slide deck for this unit: [Slides](portfolio-introduction-slides.qmd)

:::
<!-- end unit-slides div -->

::: {.unit-transcript}
# Text and Audio Transcripts

Read the text transcript: [Text transcript](portfolio-introduction-transcript.md)

<!--
Listen to the audio transcript: [Audio transcript](AUDIO_LINK)
-->

::: 
<!-- end unit-transcript div -->
::: {.unit-reading}
# Reading

## Introduction

In our context, a portfolio is an organized collection of work that showcases skills and experience. Since the work is generally code, text and other digital content, you can easily place your portfolio online.



## Why have a portfolio

It is useful to showcase your skills for several reasons.

If you are looking for a new job, the application materials you submit, such as cover letter and CV or resume, generally need to be fairly short. You can mention specific skills in those documents, but you can't really demonstrate them. But you can add a link to your application materials to point interested readers to a website that showcases your skills in more detail.

Even if you are not looking for a new job, having your work and skills out there is a good way of having potential opportunities come your way. Say someone is looking for a speaker/presenter for an event who could talk about a particular topic. They might ask colleagues for recommendations, or search online. If you have work online that shows that you are proficient in that topic, you might be contacted.

A more altruistic reason is that if you have knowledge in a certain area, sharing it publicly can potentially help others learn from you. Just think of the many times you looked for and found some useful information online. You can be the provider of such information too!


## How to make a portfolio

An online portfolio is basically a website. This could be a stand-alone page, or it could be part of your main site (if you have a personal website). Any tool that allows you to make online content and place it on a server can work. There are many free tools. WordPress is a very common platform. 

We like using Quarto and Git/GitHub. In the following unit, we will show you how to create a portfolio using these tools.

::: 
<!-- This ends the unit-reading div -->


::: {.unit-summary}
# Summary
In this unit, we covered the basics of a portfolio, what it is and why you should have one.
::: 
<!-- This ends the unit-summary div -->


::: {.unit-resources}
# Further Resources

* [The Tufts University Career Center on Portfolios](https://careers.tufts.edu/resources/what-is-an-online-portfolio/) has a few more thoughts on why having a portfolio is a good idea and some tips to consider.

* [This GitHub repository and presentation](https://github.com/deepshamenghani/Portfolio_with_Quarto_ppt) by Deepsha Menghani provides a nice overview of creating a portfolio with Quarto.


:::
<!-- This ends the unit-resources div -->


::: {.unit-quiz}
# Test yourself

```{r portfolio-introduction-quiz}
#| echo: false
#| results: "asis"
# quizzes <- list("portfolio-introduction-quiz-1.Rmd", "portfolio-introduction-quiz-2.Rmd", "portfolio-introduction-quiz-3.Rmd")
# exams2forms::exams2forms(file = quizzes, title = 'portfolio-introduction-quiz')
```
:::



::: {.unit-exercise}

# Practice
* Look around online to find a few personal webpages that showcase products a person created.
* For a very nice example - just don't get intimidated by it ðŸ˜ - check out [Andrew Heiss](https://www.andrewheiss.com/).



::: 
